### ISSUE TITLE
specs and samples

### ISSUE THREAD

**Issue by fish2000** [jackjennings/graver#1]
Dogg this is sweet to have. Your synopsis is notably tight but it does engender a pair of questions:
1. Can you throw in a link to whatever spec documents upon which your work is based, for reference?
2. Relatedly, do you have any sample data on hand you can furnish? Assuming of course that such a furnishing wouldn’t be raise a bunch of nightmarish legal problems, erm.

But yeah in any case thanks for this

**Comment by jackjennings** [comment]
I just added a link to the spec in the README, the entirety of which is viewable on this page: http://unifiedfontobject.org/versions/ufo3/glyphs/glif/

It's a fairly small, open-source, XML-based format used for defining font glyphs. You can see an example of the format here: https://github.com/jackjennings/graver/blob/master/test/fixtures/glif2.glif

Ultimately I'm using this as a prototype for defining and interface for the entire UFO format (also at the first link). The biggest hurdle to existing implementations is support multiple versions of the format simultaneously, so I'm trying to build this as declaratively as possible to make supporting future versions of the spec easier. Next steps will be figuring out a way to declare transformations between versions, and validations, and working on some way of writing file data.
